source 'http://rubygems.org'

gem 'rails', '4.1.8'
gem 'pg'
gem 'active_model_serializers', '0.9.3'

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin]
